### ISSUE TITLE
Creates rivers in the nether

### ISSUE THREAD

**Issue by QazCetelic** [delvr/Streams#102]
It's probably caused by a mod compatibility issue (I'm using a few other mods)

Seed: 2555326775271932549
Coordinates: 800, 63, 87

While using streams it creates a river but it doesn't generate a river if I'm not using streams.

**Comment by GaterG10** [comment]
I have the same issue. Does anyone know how to fix it?

**Comment by QazCetelic** [comment]
> I have the same issue. Does anyone know how to fix it?

I think that updating the library that is needed for this mod fixes the issue.
Or you need to use an older version of the library, I don’t fully remember it. The last time I used it was a while ago.
