### ISSUE TITLE
Streams + SpongeForge causes strongholds to fail to generate

### ISSUE THREAD

**Issue by Pulz-TCP** [delvr/Streams#112]
As per the title, strongholds only generate when one or the other of the aforementioned files are present. When both are present, Strongholds do not generate.

Reproducible with:

Streams 0.4.8
Farseek 2.5
SpongeForge (Have only tested 2838-7.2.3, 7.3.0 and 7.3.1-RC4079- I imagine this version doesn't matter much)

For testing purposes, here is a seed with the tp command for the nearest stronghold. Can be used as a use-case to show that the generation does not occur if one of the mods is removed and the world is regenerated with the same seed.

seed: 8049708818318992939
/tp -1304 90 -808

**Comment by Pulz-TCP** [comment]
Found this to be a farseek issue, will refer to them or SpongeForge as the notice at https://docs.spongepowered.org/stable/en/server/spongineer/incompatible.html states that this is an issue on 2.3 and 2.4. 2.5 is the proposed fix, but is present in this use-case.

**Comment by Enterprise12nx01** [comment]
So is there any fix for this? its been awhile since i have seen streams work.
im using spongeforge

**Comment by Pulz-TCP** [comment]
> So is there any fix for this? its been awhile since i have seen streams work.
> im using spongeforge

Not that I've been made aware of. My open issue can be found here https://github.com/SpongePowered/SpongeForge/issues/3223

**Comment by Enterprise12nx01** [comment]
Any update??
