### ISSUE TITLE
When using smart Moving Streams don't Connect fully, and can breath while Underwater

### ISSUE THREAD

**Issue by jasonmbrown** [delvr/Streams#15]
I am assuming this is a streams issue, But when you use Smartmoving and Streams. You can basically sit under a stream and swim up a tiny bit every few moments and you will get back all your Air Bubbles.

**Comment by delvr** [comment]
This was actually occurring regardless of Smartmoving, in Streams for 1.7.10 and 1.9.4/1.10. This is now fixed for 1.9.4/1.10, and I'll backport the fix in 1.7.10 in the next release for that version.

**Comment by delvr** [comment]
Now fixed in all versions with the 1.7.10-0.3.4 release.
