### ISSUE TITLE
1.9-1.2 crashes dedicated forge server on startup right after mods are loaded (phase 1)

### ISSUE THREAD

**Issue by kreezxil** [delvr/Streams#16]
no crash report except for these exceptions are thrown

http://pastebin.com/iNZqw6F8

**Comment by delvr** [comment]
Thanks for reporting this, it will be fixed in the next release.

**Comment by delvr** [comment]
Fixed in Farseek 1.9.4-1.1. Will now backport to 1.9.0.

**Comment by kreezxil** [comment]
Confirmed fixed. :)
