### ISSUE TITLE
An Odd Duck

### ISSUE THREAD

**Issue by kreezxil** [delvr/Streams#19]
One of my players is getting an odd crash report, I say odd, because I had Waila and removed it in favor WIT. But a mod apparently is looking for Waila, yours is the 2nd to last I recognize in the stack trace, I'm reporting this to all the mods in there as I'm not sure who should get this report.

crash report: http://pastebin.com/Q6a8an9R

**Comment by delvr** [comment]
Please refer to https://github.com/delvr/Farseek/issues/14.
