### ISSUE TITLE
Streams is 1.9.4 but Farseek is 1.9

### ISSUE THREAD

**Issue by Gamerbolts** [delvr/Streams#21]
Hi I was just trying to get your mod loaded and it crashed saying Farseek was looking for a version different than 1.10.2 Saying to remove it from my mods to get the instance to work again. I downloaded Farseek 1.9-1.1 Which I kinda figured was gonna look for 1.9 but seeing you saying that you fixed crashes on 1.10 I thought it would run.

Any assistance is appreciated. Thanks!

**Comment by delvr** [comment]
Hi Gamebolts,
you need Farseek-1.9.4. It's possible it's not the latest uploaded on CurseForge, so make sure you look at All Files and you'll find it. Let me know if this works for you.

**Comment by Gamerbolts** [comment]
I am such an idiot lol I just clicked the top download button in orange. Thank you it's working now :)

**Comment by delvr** [comment]
No worries, I edited the forum post so the 1.9.4 version shows up first now, should help clear up any confusion. Enjoy the mod!
