### ISSUE TITLE
Exception Gen New Chunk

### ISSUE THREAD

**Issue by WenXin20** [delvr/Streams#26]
It crashed on world creation with the exception generating new chunk.
Forge 2120
Mods Listed in [Crash Report](http://pastebin.com/LXRZp6au):

- Streams v0.2.1
- Farseek v1.1
- **[RTG v4.1.1.7](https://minecraft.curseforge.com/projects/realistic-terrain-generation)**
- **[Pam's HarvestCraft v1.10.2h](https://minecraft.curseforge.com/projects/pams-harvestcraft)**
- **[Mob Hunter v0.1.7](https://minecraft.curseforge.com/projects/mob-hunter)**
- **[Agricultural Revolution (Cooking Plus) v0.8.9](https://minecraft.curseforge.com/projects/the-agricultural-revolution)**

Other Terrain Mods:

- [BOP v5.0.0.2093](https://minecraft.curseforge.com/projects/biomes-o-plenty)
- [Custom Ore Gen v1.4.2](https://minecraft.curseforge.com/projects/customoregen)
- [SugiForest v1.2.2](https://minecraft.curseforge.com/projects/sugiforest)
- [Mithwood Forest v1.03](https://minecraft.curseforge.com/projects/rainbeaus-mithwood-forest)

**Comment by delvr** [comment]
This should be fixed in Streams 0.3/Farseek 2.0. Please give it a try and let me know of any issues, thanks!
