### ISSUE TITLE
Crash with Streams and ThermalDynamics covers

### ISSUE THREAD

**Issue by iszn11** [delvr/Streams#3]
Apparently, having ThermalDynamics and Streams installed creates TD cover out of some block which, when rendered, crashes Minecraft.

**To reproduce**
1. Install Streams, ThermalDynamics and dependencies (Farseek, CoFHCore and ThermalFoundation).
2. Switch to creative mode.
3. Open creative tab named _Thermal Dynamics: Covers_.
4. Minecraft will immediately crash.
[Crash report](http://pastebin.com/w3zecQXj)

If you have NEI, you can also edit config/cofh/thermaldynamics/client.cfg and set _Covers.Show_ to true. Now, scroll through pages in NEI and eventually you'll end up on page with that problematic item.

Checked with:
* CodeChickenCore 1.0.7.46
* CoFHCore 3.0.3-303
* Farseek 1.0.8
* NotEnoughItems 1.0.5.111
* Streams 0.1.4
* ThermalDynamics 1.1.0-161
* ThermalFoundation 1.2.0-102

The problem can be fixed easily by hiding TD covers both in creative and NEI, but I still wanted to report this minor problem.

**Comment by delvr** [comment]
Thanks iszn11 for reporting this - I will investigate and get back to you.

**Comment by delvr** [comment]
Fixed in v0.1.5.
