### ISSUE TITLE
Issue with string formatting.

### ISSUE THREAD

**Issue by Yankas** [delvr/Streams#30]
The error message that shows when loading an existing world shows a clearly visible carriage return [CR] character as shown in the attached image.
Might be a bug with farseek instead, but I am guessing that it appends an extra '\r' where it isn't needed. Only tested this on Windows where a new line should be '\r\n'. 

![string](https://cloud.githubusercontent.com/assets/3958914/20993505/05eae454-bceb-11e6-96f8-16f4e38764cf.png)

Versions used:
Streams-1.9.4-0.3.jar
Farseek-1.9.4-2.0.jar

**Comment by delvr** [comment]
Thanks for reporting! This is fixed in Farseek v.2.1.
