### ISSUE TITLE
latest 1.7 version (1.7.10.1.1 bugged

### ISSUE THREAD

**Issue by CcytherR** [delvr/Streams#35]
Hello, your latest Farseek (1.7.10.1.1) even with just streams mod alone, the world takes forever to generate like 3-5% intervals and no streams even seem to show and gets super laggy loading chunks despite no streams generating, compared to old version on curse which loads much quicker and smoother even with lots of mods for now i've reverted back to version 1.0.11 .

**Comment by delvr** [comment]
Thanks for reporting, please follow issue https://github.com/delvr/Farseek/issues/22 for updates.
