### ISSUE TITLE
1.11.2 Issue with shaders

### ISSUE THREAD

**Issue by Endmateria** [delvr/Streams#37]
I've tried a couple different shaders (screenshots attached) and noticed that none of them seem to be capable of rendering your streams properly.  Is there a way to fix this?  ![2017-03-20_12 20 25](https://cloud.githubusercontent.com/assets/25782793/24111880/3fb91146-0d6e-11e7-92c0-a9aa78a2d9a3.png)
![2017-03-20_12 22 03](https://cloud.githubusercontent.com/assets/25782793/24111879/3fadf6f8-0d6e-11e7-9ca2-2e6f7a226966.png)
![2017-03-20_12 23 12](https://cloud.githubusercontent.com/assets/25782793/24111878/3faabe34-0d6e-11e7-94c4-a855e9fe4166.png)

**Comment by Endmateria** [comment]
It may be the texture pack, I forgot to check/test that.  Are your water textures effected by texture packs?  I'll do some more testing on that later...

**Comment by delvr** [comment]
Hi Endmateria,

you'll need to add the Streams river block IDs to your shader configuration. Instructions for this are in the FAQ on the mod's forum post, here it is:

> **How do I make shaders work with the river blocks?** You need to specify the block IDs in your shader configuration. Look through the console or game log (log/fml-client-latest.log) for a message starting with "Shader configuration". There you will find a pre-formatted configuration line to put in the config file. Normally this file is named gbuffers_water.vsh and must be modified inside the shaderpack .zip file (so make sure to re-add it to the archive if you extracted it for modifying). The block IDs should include custom water blocks from other mods, but will change with every combination of mods so make sure you re-check it when adding/removing mods.

Just let me know if this works for you.

Cheers,
-delvr.

**Comment by Endmateria** [comment]
K, so I got the shaders working using your advice (thanks by the way)... but what's up with the water color mismatch?  Any way to correct that?
![2017-03-20_23 42 22](https://cloud.githubusercontent.com/assets/25782793/24131979/5b4d3ef0-0dc8-11e7-9347-1a78c47872ec.png)
![2017-03-20_23 42 49](https://cloud.githubusercontent.com/assets/25782793/24131980/5b4d5f02-0dc8-11e7-9e94-746cf6302668.png)
![2017-03-20_23 43 31](https://cloud.githubusercontent.com/assets/25782793/24131981/5b4ef52e-0dc8-11e7-9cfe-f5116b13eb99.png)

**Comment by delvr** [comment]
Hm, not sure why this happens... might be something specific to your shader or resource pack. Perhaps your shader pack has other water-block-related entries that require specifying block IDs? Sorry I cannot help further since I'm not very familiar with shader pack internals. But if you do find out please let me know so I can add the info to the FAQ.

**Comment by Endmateria** [comment]
Those 3 pictures are from 3 different shader packs and I have no resource pack installed, so it seems to be a general shader problem.  I'm sure you're right that more has to be modified within the shader pack to make it/them read your water blocks properly.  There's a discord channel that all the shader pack makers are involved in, I'll post the question there and let you know if I get any useful feedback.  Brilliant mod by the way, looks like it was complex AF to build.

**Comment by Endmateria** [comment]
It's kinda complex, but I think this exchange holds the solution... https://github.com/sp614x/optifine/issues/254.  I guess, rather than tampering with/adding dynamic block id's to the gbuffers_water.vsh file, the optifine/shadermod guys set up a way for you to map your water blocks (with block name rather than dynamic id) to a hardcoded vanilla water block... thereby making the shaders treat your blocks the same way they treat the vanilla block you mapped them to.  It might actually be easier for your users to set up in the long run, if you're able to wrap your head around it. I on the other hand, found it ridiculously confusing hahahaha.
