### ISSUE TITLE
1.10.2 Streams + SpongeForge

### ISSUE THREAD

**Issue by WildKarrade** [delvr/Streams#39]
This is not a crash or a major issue for most people at the moment but streams, aka streams and farseek, loads but will not generate streams when used with SpongeForge. I test several versions from the latest SpongeForge going backwards and none work.

**Comment by delvr** [comment]
Thanks for reporting! This is the same issue as https://github.com/delvr/Farseek/issues/16 which I'm currently investigating. Please head to that issue for updates, thanks!
