### ISSUE TITLE
Does this work with the new OTG?

### ISSUE THREAD

**Issue by EchenCraft** [delvr/Streams#40]
I haven't had any crashes or anything but flying around for awhile during testing I haven't found a river.

It worked wonderfully with BOP but since rebuilding this pack with OTG Im wondering if its even working.

**Comment by EchenCraft** [comment]
Still looking for an answer with this but let me be a little more specific.

I have yet to see a Streams spawn anywhere on a map generated with OTG Biomes Bundle.
No errors in console
No indication at all that streams are being generated in console

Now I have theory, though unconfirmed, that it will in fact generate them..... but only in vanilla biomes.... which is like a needle in a hay stack with Biome Bundle at 400+ biomes.

Throw in the fact that OTG uses virtual biome id's and I may be wrong on this but Im about 90% positive that Streams wouldn't know what to do with that, if it even recognized biomes above id 256 at all.

Is there any way I can tell Streams which biomes to spawn in? At least below the 256 limit?

**Comment by delvr** [comment]
I can confirm that Streams doesn't work with OTG, because that mod handles its chunk generator in a non-standard way which Streams cannot hook into. Creating a hook for it involves quite a bit of core-modding but I might be able to do it. I'll update here once I have more.

**Comment by delvr** [comment]
New Farseek version 1.12-2.2.1 adds support for OTG in Streams. Please give it a try!
