### ISSUE TITLE
1.11.2: Cascading Worldgen Lag

### ISSUE THREAD

**Issue by Darkosto** [delvr/Streams#42]
Hello, while exploring the world and generating new chunks, I constently have the following console spam:

https://pastebin.com/YPY1HFvL

My worldgen is being handled be Quark's Realistic Terrain Gen.

Streams: 0.3
Farseek: 2.1
MC: 1.11.2

Thank you!
Darkosto

**Comment by delvr** [comment]
Thanks for reporting! Please follow https://github.com/delvr/Farseek/issues/26 for updates.
