### ISSUE TITLE
Location/Seed specific crash with OTG/Biome bundle

### ISSUE THREAD

**Issue by 3nd0fw0r1d** [delvr/Streams#45]
Trying to generate terrain in certain areas makes the game completely exit out
Mods list: https://puu.sh/yy16B/0faa4cd93e.png

[latest.log](https://github.com/delvr/Streams/files/1524045/latest.log)

**Comment by delvr** [comment]
The error stack trace doesn't refer to Streams/Farseek, only to CraftTweaker. Does this crash happen without CraftTweaker?

**Comment by 3nd0fw0r1d** [comment]
Could've sworn I wasn't having issues until I added Streams, but it does indeed seem to be crafttweaker

**Comment by delvr** [comment]
Thanks for letting me know! I'll close this issue and if you later find out that Streams is involved please re-open.
