### ISSUE TITLE
[1.12.2] Streams is not compatible with shaders.

### ISSUE THREAD

**Issue by Preminenc3** [delvr/Streams#50]
Shaders will change all the water except the ones affected by streams, so there is a mix of shader water and MC default water.

**Comment by delvr** [comment]
Hi Preminenc3, you can enable shaders for Streams as per this FAQ entry from the mod forum post:

**How do I make shaders work with the river blocks?** Starting with Streams 0.4 for Minecraft 1.9.4 or more recent, a block.properties file is provided in the mod's .jar archive (which you can open like a .zip file). Just copy that file to your shaderpack's "shaders" directory and you should be good to go. Note that you'll need a reasonably recent version of both OptiFine and your shaderpack (the block.properties file will specify the minimum OF version, if any). Note also that not all shaders will properly display Streams river current even if they render the water itself. For example SEUS shaders version 10.1 will show currents but 11.0 will not. (This is not something Streams has any control over). Also note: if shaders stop working for Streams blocks after a restart, disable and re-enable your shaderpack to fix this.
