### ISSUE TITLE
Quark

### ISSUE THREAD

**Issue by AlexRover** [delvr/Streams#51]
Hello, is there no way to do support for Quark? on version 1.12 in my opinion there is no better landscape generator, but your mod does not support it, played with it in TerraFirmaCraft, it's just great

**Comment by delvr** [comment]
I just tested with the latest version of Quark and got streams with both the vanilla and Realistic world generators. What issue did you encounter with it exactly?

**Comment by AlexRover** [comment]
It's strange, I'm flying around the world already davolno long but did not meet any of your rivers, I have a question, do I need to customize the mod or just download it and the API and everything will work?

**Comment by AlexRover** [comment]
Really found, but how it rarely meets, or I was so unlucky, the map does not see water in the river

**Comment by AlexRover** [comment]
Fish can not cope with the current (
![2017-12-30_06 44 36](https://user-images.githubusercontent.com/34899332/34450180-f6448834-ed2c-11e7-8506-e1b7ced669bc.png)
![2017-12-30_06 44 34](https://user-images.githubusercontent.com/34899332/34450184-04c044ac-ed2d-11e7-8d14-20f5489b9b72.png)

**Comment by AlexRover** [comment]
sorry there are no networks)

**Comment by delvr** [comment]
Glad to hear you found some streams. Not sure if I can do anything about the fish though. I'll close this issue, please let me know if you encounter other incompatibilities with Quark.
