### ISSUE TITLE
[ERROR] World Building Failure [Streams]

### ISSUE THREAD

**Issue by Frederick404** [delvr/Streams#52]
All Mods I Have Installed Are "Farseek" And "Streams" 
Yet It Still Doesnt Load The World
I Havent Found The Reason Myself

https://pastebin.com/kTYxGBNL

**Comment by delvr** [comment]
This looks similar to https://github.com/delvr/Farseek/issues/34 - do you have an unused Repose jar file somewhere in your mods directory or subdirectories? If so please try removing it.

**Comment by Frederick404** [comment]
Im Going To Try That
EDIT: Yeah That was The Problem You Should Fix it Sometime...
or add this Error To The Description so that others dont make the same mistake

**Comment by delvr** [comment]
Thanks for letting me know. I'll try to fix this error but oddly I haven't been able to reproduce it on my end - if a mod is present for the Farseek coremod to inspect it it gets correctly loaded by Forge , and if there are duplicates like in delvr/Farseek#34 they get rejected by Forge.

**Comment by delvr** [comment]
Hi Niduin, the new Farseek 2.2.4 release includes a fix for this error; the crash should no longer happen when unused Farseek-type jars are lying around. If you find it re-occurring please re-open this issue. Thanks!
