### ISSUE TITLE
Endless loading World screen - Generating a new World

### ISSUE THREAD

**Issue by Niduin** [delvr/Streams#53]
If  i start a new world - i get an endless load world screen and nothing happens

[latest.log](https://github.com/delvr/Streams/files/1697272/latest.log)

**Comment by Niduin** [comment]
I´ve found that this issue happens with Custom Mob Spawner from Mo´s Creature. If i disable CMS it works.

**Comment by delvr** [comment]
Hey Niduin, thanks for letting me know. I was looking at this one the other day and it looks like it could happen with any mod that causes chunk loading during chunk provider initialization; I'll try to put a workaround for that in the next version.

**Comment by delvr** [comment]
Hi Niduin, the new Farseek 2.2.4 release includes a fix for this sort of behavior. Please give it a try and re-open this issue if this still happens. Thanks!
