### ISSUE TITLE
Shader support can be integrated with the mod itself

### ISSUE THREAD

**Issue by ChloeDawn** [delvr/Streams#55]
You currently leave `block.properties` in the root of the mod jar and request it is copied into the user's shaderpack. You can actually store it under `assets/streams/shaders/block.properties` and have it work directly from your mod, as explained in [OptiFineDoc/doc/shaders.txt#L471](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L471).

**Comment by delvr** [comment]
Well whaddaya know! I can't believe I missed out on that feature for so long. This will be in the next version of Streams. Thanks so much for the info!

**Comment by delvr** [comment]
The `block.properties` file is now in its proper location in Streams 1.12-0.4.3. Thanks again InsomniaKitten for reporting this!
