### ISSUE TITLE
Crash on generating world

### ISSUE THREAD

**Issue by CcytherR** [delvr/Streams#59]
https://pastebin.com/E8tJawhA

**Comment by kreezxil** [comment]
Confirmed crash while generating world in version 1.12-0.4.3 of streams in ssp.

https://pastebin.com/q26bVC9v

**Comment by HypeWolf** [comment]
Yeah, happening to me aswell...
Ignore the massive amount of mods installed xd.
https://pastebin.com/8rpesy9u

**Comment by delvr** [comment]
This is the same as https://github.com/delvr/Farseek/issues/37 and will be fixed in the next day or two. Please use Forge 2651 in the meantime. Thanks for your patience!

**Comment by Excaliburning** [comment]
Hi !

I also have a worlgen crash using Forge 2611 with Sponge 2990.
The content displayed by the console : https://gist.github.com/Excaliburning/8d65531146f551a528bf62f37049b5b3
Crash report/log generated : https://gist.github.com/Excaliburning/784132c95cc8c02ccaf368fc24618c09

Could you please confirm this (my) issue is similar to #59 or delvr/Farseek#37 ? Asking here to avoid creating another duplicate.

**Comment by delvr** [comment]
Fixed in Farseek 2.2.5.

@Excaliburning yours is a different issue, specific to Sponge compatibility. Could you please open a new issue for this? Thanks!
