### ISSUE TITLE
TFC Falling Blocks & Tall Grass

### ISSUE THREAD

**Issue by lmbrjcksn** [delvr/Streams#63]
With just Streams 3.3, Farseek 2.0.1, and the latest 1.7.10 TFC installed, there's a really odd bug. When dirt, gravel, or another TFC block falls using TFC physics and lands on TFC tall grass or ferns, and possibly other blocks that things like gravel would normally break, it doesn't break. It just jumps back up and falls again, forever.

It's odd its your mod, I had to go through a long list of them to figure out which one. With just the TFC mod installed, it's fine. When I add your two, it starts doing it in both single and multiplayer on a dedicated server.

**Comment by delvr** [comment]
Interesting find! I just tested it and yeah, this shouldn't happen. Let me dust off my 1.7.10 project and see if I can fix it. :)

**Comment by lmbrjcksn** [comment]
I noticed you were still updating it for TFC, so at least you know some of us are still using it and it's still appreciated :D Thanks for taking a look at it.

**Comment by delvr** [comment]
Alright, just released Streams 1.7.10-0.3.4 which should fix this. :-) Please give it a try and let me know if there's still any issues.
