### ISSUE TITLE
Crash on server.

### ISSUE THREAD

**Issue by DrakeEldridge** [delvr/Streams#64]
Hi. So I am using streams in my modpack, and it works on the client side and on my localhost server, but the actual dedicated server I am using crashes with no crash-report, but it seems to be farseek according to the log. When I remove Farseek and Streams, everything works fine. 

Here is the log:

https://pastebin.com/5YAicRkJ

**Comment by delvr** [comment]
Fixed in Farseek 2.3.1 - please let me know if you encounter other issues.
