### ISSUE TITLE
The Farseek link on the main curseforge page leads to a dead page.

### ISSUE THREAD

**Issue by Bluberry-Kat** [delvr/Streams#68]
Currently it leads [here,](https://www.curseforge.com/minecraft/mc-mods/minecraft/229708-farseek) when instead it should be leading to either [this](https://www.curseforge.com/minecraft/mc-mods/farseek) or [this.](https://minecraft.curseforge.com/projects/farseek)

**Comment by delvr** [comment]
Fixed now, thanks for letting me know!
