### ISSUE TITLE
streams crash in modpack; Recentibus 

### ISSUE THREAD

**Issue by TheOneTraveler** [delvr/Streams#73]
i am working on getting this mdopack up and running and have encountered this issue which the crash report blames on streams. please help me get this thing running asap so it can get out of beta and into full release
crash report here:

https://pastebin.com/98K9ziTX

thanks! xo

edit: it looks like it might be an incompatibility with dynamic trees? i'll contact that mod author as well.

**Comment by delvr** [comment]
Hi TheOneTraveler, the `java.util.stream` in your crashlog is actually a standard Java class and not related to the Streams mod. I do however see mentions of DynamicTrees and ArchitectureCraft in there so please check with the authors of these mods. Thanks!
