### ISSUE TITLE
Streams v 1.12 - 0.4.5 crashes on startup

### ISSUE THREAD

**Issue by viceroy369** [delvr/Streams#75]
https://paste.dimdev.org/tufufoqimu.mccrash

**Comment by delvr** [comment]
Thanks for reporting this. Could you link to your full game log  (not just the crash log) so I can investigate further?

**Comment by WenXin20** [comment]
I had this happen to me too. It seems to be happening (at least for me) if the Minecraft launcher tries to bring up the dirt-textured warning screen for duplicate mods, missing mods, an outdated forge version, etc.

**Comment by delvr** [comment]
An interesting clue, thanks @WenXin20 ! I'll investigate but in the meantime a game log will definitely help.

**Comment by SkarletShadows** [comment]
I'm also having the issue, here's my logs.https://pastebin.com/LtCEitH4

**Comment by delvr** [comment]
Just released 0.4.7 to fix this; let me know if it happens again.

**Comment by SkarletShadows** [comment]
Seems fixed, Thank you <3
