### ISSUE TITLE
Strange Streams behavior with RTG

### ISSUE THREAD

**Issue by Haggle1996** [delvr/Streams#8]
See Team-RTG/Realistic-Terrain-Generation#352 for details. 

Basically, streams are generating way outside the expected generation area, to the left of the map, when negative seeds are used.

**Comment by infinus5** [comment]
i ve found a similar issue with RTG and Streams. 

http://i.imgur.com/EWNZeKD.png
http://i.imgur.com/FagFsNX.png

we think it might be a pregen issue, but other areas of the map are like this which were generated correctly.

**Comment by delvr** [comment]
Reported fixed on the RTG side.
