### ISSUE TITLE
Server Crash/Freez: related to Streams

### ISSUE THREAD

**Issue by SirAron111** [delvr/Streams#83]
Server Crash/Freez: related to Streams
I don’t know what’s causing it to Freez and Crash but the log spams around Stream erroring messages.
https://pastebin.com/QFa96NxD

Streams-1.12-0.4.7.jar
Forge 14.23.5.2838

**Comment by Vagor96** [comment]
This could be related to #74 
Which mods do you use?

**Comment by SirAron111** [comment]
The complet mod list can be found here on the very bottom https://www.curseforge.com/minecraft/modpacks/dimension-zero a user reported this crash issue

**Comment by dkambersky** [comment]
Looks like a dupe of #74.

**Comment by Vagor96** [comment]
Does the issue persist if you remove AutoRegLib?

**Comment by delvr** [comment]
Please see #74 for updates. Closing as duplicate.
